export type QuizQuestion = { q: string; a: string[]; correct: number };
export type Lesson = { id: string; title: string; minutes: string; kind: "Video" | "Workshop" | "Quiz"; video: string; goal: string; action: string[]; deliverable: string; quiz: QuizQuestion[] };
export type Module = { id: number; title: string; summary: string; color: string; lessons: Lesson[] };

const moduleInfo = [
  ["E-commerce Foundations", "Choose a model, market and starting constraint before you build.", "#c9ff54", "RWI59fC7Z48"],
  ["Winning Product Research", "Find evidence of demand before spending on ads or inventory.", "#8fe3ff", "E6PD7DepcI0"],
  ["Brand & Offer Design", "Build a clear promise, price and offer customers understand.", "#f2acff", "zpUsN6xQSGQ"],
  ["Build Your Shopify Store", "Go from a blank account to a conversion-ready storefront.", "#c9ff54", "uorQJ_ucDhg"],
  ["Supplier & Fulfillment OS", "Source responsibly and protect the customer experience.", "#ffb976", "DHn5nPXWmeQ"],
  ["Creative That Sells", "Turn customer problems and benefits into useful creative.", "#8fe3ff", "vUbLw80KTpo"],
  ["Organic Launch Engine", "Validate messaging with TikTok, Reels and Shorts.", "#f2acff", "Y3GLZGxq0jo"],
  ["Paid Ads Without Guessing", "Test small, read the numbers and protect capital.", "#ffb976", "8dJxOaZrK1M"],
  ["Operations & Customer Care", "Run orders, support and cash flow with confidence.", "#c9ff54", "OE4WimLYVGE"],
  ["Scale Into a Real Brand", "Systemize what works and build your next growth loop.", "#8fe3ff", "u-Qfdn44rB4"],
] as const;

const lessonSets = [
  [["The Modern E-commerce Map", "Video", "Pick the model that matches your capital, time and risk tolerance.", ["Compare inventory, pre-order and supplier-fulfilled models.", "Write your available starting capital and weekly hours.", "Choose one model to test for the next 30 days."], "One-page business model decision"], ["Dropshipping vs. Inventory", "Workshop", "Use a decision matrix instead of choosing from social-media hype.", ["List landed-cost, delivery and return risks for both options.", "Score each option from 1–10 for your current situation.", "Circle the option with the smaller first test."], "Model scorecard"], ["Choose Your Business Model", "Workshop", "Define a focused launch lane you can execute this month.", ["Write one audience, one product category and one sales channel.", "Remove every idea that does not fit the launch lane.", "Set a test deadline on your calendar."], "30-day launch lane"], ["Foundation Checkpoint", "Quiz", "Confirm your first decisions before product research.", ["Answer the knowledge check.", "Revisit any answer you missed.", "Mark the foundation complete."], "Foundation decision confirmed"]],
  [["The Five-Signal Product Scorecard", "Video", "Separate real demand signals from a product that only looks trendy.", ["Open Product Lab and score three ideas.", "Capture a TikTok, Amazon, Google and supplier signal for each.", "Keep only products with defensible margin."], "Three-product evidence sheet"], ["Find Demand Before You Spend", "Workshop", "Research search interest, social proof and competitive density.", ["Search the buyer problem on TikTok Creative Center.", "Open Amazon Movers for the category.", "Write two demand signals and one risk."], "Demand proof log"], ["Supplier Validation Lab", "Workshop", "Ask questions that protect your first order.", ["Find three supplier listings.", "Compare sample price, lead time, MOQ and customization.", "Draft a sample request."], "Supplier comparison"], ["Build Your Test List", "Quiz", "Decide which product deserves a controlled test.", ["Complete the scorecard quiz.", "Rank your shortlist by evidence.", "Add one winner to Inventory."], "Test candidate selected"]],
  [["Name, Position & Promise", "Video", "Write a brand promise that a buyer can repeat.", ["Name the customer and specific problem.", "Draft: For [customer], we help [outcome].", "Remove vague words."], "Positioning statement"], ["Bundle and Price the Offer", "Workshop", "Turn a product into an offer with enough margin to test.", ["Enter economics in Profit Tracker.", "Choose a bundle, bonus or guarantee.", "Set a price that protects margin."], "Offer stack"], ["Trust Architecture", "Workshop", "Identify proof a cautious buyer needs before purchase.", ["List three customer objections.", "Match each with a proof element.", "Plan where the proof belongs."], "Trust map"], ["Offer Teardown Quiz", "Quiz", "Check that your offer is clear, credible and sound.", ["Take the offer knowledge check.", "Rewrite your promise if unclear.", "Save offer draft in Journal."], "Offer approved"]],
  [["Shopify Setup & Settings", "Video", "Create the store foundation before styling it.", ["Complete business details.", "Set primary market and support email.", "Turn on fulfillable payment methods."], "Store settings checklist"], ["Theme and Navigation", "Workshop", "Build a storefront that makes the next click obvious.", ["Choose one fast mobile theme.", "Create Home, Shop, FAQ and Contact.", "Test every link on mobile."], "Navigation map"], ["The Product Page That Converts", "Workshop", "Build a page around clarity, proof and a next step.", ["Write a benefit-led headline.", "Add delivery and return detail.", "Add proof images."], "Conversion-ready product page"], ["Payments, Taxes & Policies", "Quiz", "Verify the store can accept orders with clear conditions.", ["Take store-readiness check.", "Read policies as a customer.", "Place a test order."], "Store compliance pass"]],
  [["Supplier Outreach System", "Video", "Create a supplier process that gets comparable answers.", ["Use the outreach resource.", "Send the same request to three suppliers.", "Record every answer."], "Three supplier replies"], ["Samples and Quality Control", "Workshop", "Inspect a sample as a customer, not an excited founder.", ["Check packaging, function and defects.", "Record an unboxing review.", "Decide pass, revise or reject."], "Sample quality review"], ["Shipping, Returns & Tracking", "Workshop", "Set expectations that prevent support tickets.", ["Document lead time and delivery window.", "Write a plain-language update.", "Create return decision tree."], "Customer delivery policy"], ["Fulfillment Failure Drill", "Quiz", "Practice response before a late or damaged order.", ["Take scenario quiz.", "Write escalation message.", "Save response in support macros."], "Failure-response playbook"]],
  [["Hooks, Angles & Awareness", "Video", "Start creative with a problem, outcome or contrast.", ["Write five customer-problem hooks.", "Label each hook type.", "Choose two to film."], "Hook bank"], ["The UGC Shot List", "Workshop", "Plan footage that edits into multiple ads.", ["List demonstration moments.", "Add reaction, objection and payoff shots.", "Create a 20-minute filming brief."], "UGC shot list"], ["Product Photo System", "Workshop", "Build images that explain product without paragraphs.", ["Plan hero, detail, scale, use-case and proof photos.", "Write each caption.", "Identify one missing image."], "Product image plan"], ["Build a Ten-Ad Creative Bank", "Quiz", "Create enough variety to learn which message works.", ["Take creative testing check.", "Map ten concepts across three angles.", "Schedule production."], "10-creative production plan"]],
  [["Your 30-Day Content Calendar", "Video", "Build a realistic cadence you can sustain.", ["Choose three content pillars.", "Assign one format daily for 30 days.", "Batch your first seven posts."], "30-day content calendar"], ["Short-form Retention Formula", "Workshop", "Design early seconds so viewers understand why to stay.", ["Write a tension-led first line.", "Show product/outcome in first three seconds.", "Cut one version under 20 seconds."], "Three short-form scripts"], ["Creator Seeding Outreach", "Workshop", "Contact creators with a useful clear offer.", ["Find ten relevant creators.", "Personalize outreach.", "Track sent, replied and shipped."], "Creator outreach tracker"], ["Organic Launch Checkpoint", "Quiz", "Confirm cadence, variety and a feedback loop.", ["Take organic launch check.", "Choose one weekly metric.", "Commit to 30 days."], "Organic launch plan"]],
  [["Tracking and Attribution", "Video", "Know what must be measured before paid traffic.", ["List needed conversion events.", "Confirm analytics and pixel connection.", "Write baseline conversion target."], "Measurement checklist"], ["The First $100 Test Plan", "Workshop", "Limit the test so one result cannot damage budget.", ["Set a $100 ceiling and window.", "Choose product, offer and creatives.", "Define your stop rule."], "Controlled test plan"], ["Creative Testing Matrix", "Workshop", "Change one variable at a time to learn.", ["Create three creative angles.", "Keep offer and audience stable.", "Record CTR, CPC, conversion and comments."], "Creative matrix"], ["Kill, Keep or Scale", "Quiz", "Use pre-set rules to decide without emotion.", ["Take paid-testing check.", "Review your decision rule.", "Log next action in Journal."], "Ad test decision"]],
  [["Daily Operator Checklist", "Video", "Run a calm daily operating routine.", ["Set blocks for orders, support and metrics.", "Choose one daily metric.", "Create an exception list."], "Daily operator checklist"], ["Customer Support Macros", "Workshop", "Write fast replies that sound human and accountable.", ["Draft delivery, damage and refund macros.", "State action and timing.", "Ask someone to check clarity."], "Support macro pack"], ["Refunds, Disputes & Fraud", "Workshop", "Protect trust while documenting decisions.", ["Write refund eligibility.", "Create evidence folder.", "Set same-day review habit."], "Dispute handling SOP"], ["Profit and Inventory Control", "Quiz", "Confirm the store protects cash and customer experience.", ["Take operations check.", "Review stock, margin and refund rate.", "Set one reorder or pause decision."], "Weekly operating review"]],
  [["Scale Readiness Scorecard", "Video", "Scale only after economics and operations are stable.", ["Score demand, margin, fulfillment and creative.", "Identify weakest link.", "Choose one improvement first."], "Scale readiness score"], ["Email and Retention Flows", "Workshop", "Create useful post-purchase communication.", ["Outline welcome, shipping and post-purchase messages.", "Write one recovery message.", "Define timing."], "Retention flow map"], ["Team, SOPs & Automation", "Workshop", "Document work so growth does not create chaos.", ["Choose one repeated task.", "Write trigger, owner, steps and quality check.", "Test it with another person."], "First operating SOP"], ["Your 90-Day Growth Plan", "Quiz", "Leave with experiments rather than a vague scale goal.", ["Take final check.", "Set 30-, 60-, 90-day milestones.", "Schedule weekly review."], "90-day operating plan"]],
] as const;

const Q = (q: string, a: string[], correct: number): QuizQuestion => ({ q, a, correct });
const questionSets: QuizQuestion[][] = [
  [Q("What should determine your first commerce model?", ["A viral post", "Your available capital, time and risk", "The cheapest software", "A competitor's logo"], 1), Q("A focused launch lane contains:", ["Many products for everyone", "One audience, category and sales channel", "Only an ad budget", "A warehouse lease"], 1), Q("Best next decision?", ["Order inventory now", "Choose one model and a 30-day test", "Copy a competitor", "Raise prices"], 1)],
  [Q("Which is a demand signal?", ["A product you like", "Repeated buyer problem and active creative", "Low price alone", "A logo trend"], 1), Q("Why order a sample?", ["Avoid comparison", "Check quality and delivery reality", "Skip returns", "Set ad budget"], 1), Q("Select a test candidate by:", ["Excitement", "Evidence and margin room", "Listing title", "Colors"], 1)],
  [Q("A useful promise names:", ["A buyer and outcome", "Only the founder", "Every feature", "A slogan"], 0), Q("A stronger offer has:", ["Vague claims", "Value, proof and economics", "Lowest price", "No objections"], 1), Q("Trust architecture means:", ["More popups", "Objections matched with proof", "Copy a store", "Hide policies"], 1)],
  [Q("Before styling, you should:", ["Set operating details and payments", "Buy ads", "Remove policies", "Add every app"], 0), Q("Mobile navigation should make:", ["Every click obvious", "Pages longer", "Policies hidden", "Checkout optional"], 0), Q("A conversion page needs:", ["Only photos", "Clarity, proof and next step", "No delivery info", "Autoplay video"], 1)],
  [Q("Supplier answers compare when:", ["Same brief sent", "Random questions", "One supplier", "MOQ skipped"], 0), Q("Quality control tests:", ["Packaging, function and defects", "Only color", "Only price", "Supplier photos"], 0), Q("Shipping communication needs:", ["Clear expectation", "No tracking", "Hidden timing", "Impossible promise"], 0)],
  [Q("A hook starts with:", ["Customer tension or outcome", "Company history", "Long disclaimer", "Random trend"], 0), Q("UGC shot list helps:", ["Capture proof and demo", "Avoid filming", "Use one angle", "Skip context"], 0), Q("Creative bank gives:", ["Messages to test", "One eternal ad", "More inventory", "Tax policy"], 0)],
  [Q("Content pillars are:", ["Repeatable customer-relevant topics", "Hashtags", "Paid setting", "Supplier contract"], 0), Q("Retention improves when:", ["Product appears early", "Hook delayed", "All videos identical", "Captions removed"], 0), Q("Outreach should be:", ["Personalized and clear", "Mass spam", "Emoji only", "Threatening"], 0)],
  [Q("Controlled test needs:", ["Fixed budget and stop rule", "Unlimited spend", "Ten product changes", "No measurement"], 0), Q("Fair creative test keeps stable:", ["Offer and audience", "Everything at once", "Product category", "Business model"], 0), Q("Scale decision follows:", ["Evidence rules", "One comment", "Hunch", "Competitor price"], 0)],
  [Q("Daily routine includes:", ["Orders, support and metric review", "Only social scrolling", "No exceptions", "Random tasks"], 0), Q("Support macro states:", ["Next action and timing", "Nothing", "Hidden policy", "Blame"], 0), Q("Inventory control protects:", ["Cash and customer experience", "Followers", "Logos", "Views"], 0)],
  [Q("Ready to scale when:", ["Demand, margin and operations stable", "One ad likes", "Product arrives", "Want revenue"], 0), Q("Retention flow is:", ["Useful and timed", "Only discounts", "Random", "Hidden"], 0), Q("An SOP documents:", ["Trigger, owner, steps and quality", "Only title", "A wish", "An ad metric"], 0)],
];

export const modules: Module[] = moduleInfo.map(([title, summary, color, video], moduleIndex) => ({
  id: moduleIndex + 1, title, summary, color,
  lessons: lessonSets[moduleIndex].map(([lessonTitle, kind, goal, action, deliverable], lessonIndex) => ({
    id: `${moduleIndex + 1}-${lessonIndex + 1}`, title: lessonTitle,
    minutes: kind === "Quiz" ? "3 questions" : `${12 + moduleIndex + lessonIndex * 4} min`,
    kind: kind as Lesson["kind"], video, goal, action: [...action], deliverable, quiz: questionSets[moduleIndex],
  })),
}));

export type ResearchCandidate = { name: string; category: string; score: number; cost: number; price: number; velocity: string; saturation: string };

export const flashcards = [
  ["Contribution margin", "Revenue left after variable costs: product, shipping, fees and ad spend."],
  ["AOV", "Average order value: total revenue divided by total orders."],
  ["Break-even ROAS", "The return on ad spend where an order neither gains nor loses money."],
  ["Landed cost", "Product cost plus freight, duties, packaging and handling."],
  ["Conversion rate", "The percentage of store sessions that become orders."],
];
